{{- if .Values.app.smtp.secret.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.smtp.secret.secretName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ "vaultwarden@example.com" | b64enc | quote }}
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.app.smtp.secret.secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData .Values.app.smtp.secret.secretName) | default (randAlphaNum 32 | b64enc) }}
  password: {{ $jwtSecret | quote }}
{{- end }}
