apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.websocket.port }}
      targetPort: 3012
      protocol: TCP
      name: websocket
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
