{{ if .Values.ingress.certManager.enabled }}
{{- $fullName := include "mailu.fullname" . -}}
{{- $certManagerLabels := include "mailu.labels" . -}}

---
apiVersion: {{ .Values.ingress.certManager.apiVersion }}
kind: Certificate
metadata:
  name: {{ $fullName }}-certificates
  labels:
    {{- $certManagerLabels | nindent 4 }}
  {{- with .Values.ingress.certManager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ $fullName }}-certificates
  # re-new certificate when it expires in less than 60 days
  renewBefore: 1440h0m0s
  commonName: "{{ first (required "hostnames" .Values.hostnames) }}"
  dnsNames:
{{- range .Values.hostnames }}
  - "{{ . }}"
{{- end }}
  issuerRef:
    name: {{ .Values.ingress.certManager.issuerRef.name }}
    kind: {{ .Values.ingress.certManager.issuerRef.kind | default "ClusterIssuer" }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"
{{- end }}   
