apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport
data:
  teleport.yaml: |-
    teleport:
      log:
        output: stderr
        severity: INFO

    auth_service:
      enabled: true
      cluster_name: teleport.example.com
      tokens:
      # These commands will generate random 32-chacter alphanumeric strings to use as join tokens
      - "proxy,node:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
      - "trusted_cluster:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
      listen_addr: 0.0.0.0:3025
      public_addr: teleport.example.com:3025

    proxy_service:
      enabled: true
      # listen_addr: 0.0.0.0:3080
      public_addr: teleport.example.com:30443

    ssh_service:
      enabled: true
      labels:
        cluster: custom
      commands:
      - name: kernel
        command: [/bin/uname, -r]
        period: 5m
