apiVersion: v1
kind: Service
metadata:
  name: {{ include "anonaddy.fullname" . }}-mariadb
  labels:
    {{- include "anonaddy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mariadb
  selector:
    {{- include "anonaddy.selectorLabelsMariaDB" . | nindent 4 }}
