# Default values for zerotier-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ui:
  replicaCount: 1
  image:
    repository: dec0dos/zero-ui
    pullPolicy: IfNotPresent
    tag: "1.5.1"
  persistence:
    enabled: true
    pv:
      create: false
      name: zerotier-ui-pv
    pvc:
      create: true
      name: zerotier-ui-pvc
      size: 200Mi
  admin:
    generate: true
    secretName: zerotier-admin-credentials
    usernameSecretKey: username
    passwordSecretkey: password

controller:
  replicaCount: 1
  image:
    repository: zyclonite/zerotier
    pullPolicy: IfNotPresent
    tag: "1.14.1"
  persistence:
    enabled: true
    pv:
      create: false
      name: zerotier-one-pv
    pvc:
      create: true
      name: zerotier-one-pvc
      size: 100Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    []
    # - host: zerotier.example.com
  tls:
    enabled: false
    redirect: false
    mode: SIMPLE
    # secretName: zerotier-tls
  istioGateway:
    enabled: false
    annotations: {}
  certManager:
    enabled: false
    # issuerRef:
    #   name: cloudflare-letsencrypt-prod
    #   kind: ClusterIssuer
    annotations: {}

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
