{{- if .Values.dns.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}-coredns
  name: {{ include "netmaker.fullname" . }}-coredns
spec:
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
    name: udp
  - port: 53
    protocol: TCP
    targetPort: 53
    name: tcp
  selector:
    app: {{ include "netmaker.fullname" . }}-coredns
  sessionAffinity: None
  type: ClusterIP
  clusterIP: {{ required "A valid .Values.dns.clusterIP entry required! Choose an IP from your k8s service IP CIDR" .Values.dns.clusterIP}}
{{- end }}
