teleport:
  log:
    output: stderr
    severity: INFO
auth_service:
  enabled: true
  {{- with (first .Values.ingress.hosts) }}
  cluster_name: {{ .host }}
  {{- end }}
  tokens:
  # These commands will generate random 32-chacter alphanumeric strings to use as join tokens
  - "proxy,node:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
  - "trusted_cluster:$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
  listen_addr: 0.0.0.0:3025
  {{- with (first .Values.ingress.hosts) }}
  public_addr: {{ .host }}:3025
  {{- end }}
proxy_service:
  enabled: true
  # listen_addr: 0.0.0.0:3080
  {{- with (first .Values.ingress.hosts) }}
  public_addr: {{ .host }}:443
  {{- end }}
ssh_service:
  enabled: true
  labels:
    cluster: custom
  commands:
  - name: kernel
    command: [/bin/uname, -r]
    period: 5m
