{{- if index .Values "postgresql-ha" "postgresql" "generateSecret" }}
{{- $existingSecret := index .Values "postgresql-ha" "postgresql" "existingSecret" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $existingSecret }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $existingSecret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $passwordSecret to existing secret data or generate a random one when not exists
  {{- $passwordSecret := (get $secretData $existingSecret) | default (randAlphaNum 32 | b64enc) }}
  # set $repmgrPasswordSecret to existing secret data or generate a random one when not exists
  {{- $repmgrPasswordSecret := (get $secretData $existingSecret) | default (randAlphaNum 32 | b64enc) }}
  password: {{ $passwordSecret | quote }}
  repmgr-password: {{ $repmgrPasswordSecret | quote }}
{{- end }}
