imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

teleport-cluster:
  # https://github.com/gravitational/teleport/blob/master/examples/chart/teleport/values.yaml
  service:
    type: ClusterIP
  persistence:
    enabled: false
    existingClaimName: teleport-pvc

service:
  type: ClusterIP
  port: 443

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - host: teleport.example.com
  tls:
    enabled: true
    redirect: false
    mode: PASSTHROUGH
  istioGateway:
    enabled: false
    annotations: {}
  certManager:
    enabled: false
    # issuerRef: 
    #   name: cloudflare-letsencrypt-prod
    #   kind: ClusterIssuer
    annotations: {}

resources: {}
