{{- if .Values.enabled.documents }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onlyoffice.fullname" . }}-documents
  labels:
    {{- include "onlyoffice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "onlyoffice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "onlyoffice.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "onlyoffice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-documents
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.documents.repository }}:{{ .Values.image.documents.tag }}"
          imagePullPolicy: {{ .Values.image.documents.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: JWT_ENABLED
              value: "{{ .Values.jwt.enabled }}"
            - name: JWT_HEADER
              value: {{ .Values.jwt.header }}
            - name: JWT_SECRET
              value: {{ .Values.jwt.secret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
# "/app/onlyoffice/DocumentServer/data"
# "/app/onlyoffice/DocumentServer/logs"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
