{{- if .Values.redis.enabled -}}
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: {{ include "anonaddy.fullname" . }}-redis
  labels:
    {{- include "anonaddy.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "anonaddy.fullname" . }}-redis
  selector:
    matchLabels:
      {{- include "anonaddy.selectorLabelsRedis" . | nindent 6 }}
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "anonaddy.selectorLabelsRedis" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "anonaddy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: 6379
          name: redis
        # volumeMounts:
        # - name: www
        #   mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 1Gi
  #     storageClassName: thin-disk
{{- end }}