---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "netmaker.fullname" . }}-mqtt
    app.kubernetes.io/name: {{ include "netmaker.fullname" . }}-mqtt
  name: {{ include "netmaker.fullname" . }}-mqtt-config
data:
  mosquitto.conf: |
    per_listener_settings false
    listener 8883
    protocol websockets
    allow_anonymous false
    listener 1883
    protocol websockets
    allow_anonymous false
    plugin /usr/lib/mosquitto_dynamic_security.so
    plugin_opt_config_file /mosquitto/data/dynamic-security.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "netmaker.fullname" . }}-mqtt
    app.kubernetes.io/name: {{ include "netmaker.fullname" . }}-mqtt
  name: {{ include "netmaker.fullname" . }}-mqtt-wait
data:
  wait.sh: |
    #!/bin/ash
    wait_for_netmaker() {
      echo "SERVER: ${NETMAKER_SERVER_HOST}"
      until curl --output /dev/null --silent --fail --head \
        --location "${NETMAKER_SERVER_HOST}/api/server/health"; do
        echo "Waiting for netmaker server to startup"
        sleep 1
      done
    }
    main(){
    # wait for netmaker to startup
    apk add curl
    wait_for_netmaker
    echo "Starting MQ..."
    # Run the main container command.
    /docker-entrypoint.sh
    /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    }
    main "${@}"
