apiVersion: v1
kind: Service
metadata:
  name: {{ include "netmaker.fullname" . }}-mqtt
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqtt2
    port: 8883
    protocol: TCP
    targetPort: mqtt2    
  selector:
    app: {{ include "netmaker.fullname" . }}-mqtt
  sessionAffinity: None