apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs.fullname" . }}
  labels:
    {{- include "nfs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.nfs }}
      targetPort: nfs
      protocol: TCP
      name: nfs
    - port: {{ .Values.service.port.mountd }}
      targetPort: mountd
      protocol: TCP
      name: mountd
    - port: {{ .Values.service.port.rpcbind }}
      targetPort: rpcbind
      protocol: TCP
      name: rpcbind
  selector:
    {{- include "nfs.selectorLabels" . | nindent 4 }}
