name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/ct.yaml
        
  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.12.10
          - v1.13.12
          - v1.14.10
          - v1.15.11
          - v1.16.8
          - v1.17.4
          - v1.18.20
          - v1.19.16
          - v1.20.15
          - v1.21.10
          - v1.22.7
          - v1.23.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  minikube-deploy:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - lint-docs
      - kubeval-chart
    name: build example and deploy to minikube
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          kubernetes-version: v1.22.7
      - uses: zufardhiyaulhaq/setup-istioctl@v1.0.0
        with:
          version: '1.13.2'
      - name: Deploy chart
        run: .github/minikube.sh
      - name: Check pods
        run: kubectl get pods -n default
      # - name: Build image
      #   run: |
      #     export SHELL=/bin/bash
      #     eval $(minikube -p minikube docker-env)
      #     docker build -f ./Dockerfile -t local/example .
      #     echo -n "verifying images:"
      #     docker images        
      # - name: Test service URLs
      #   run: |
      #     minikube service list
      #     minikube service example --url
      #     echo "------------------opening the service------------------"
      #     curl $(minikube service example --url)