name: Lint and Test Charts

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    paths:
      - 'charts/**'

jobs:

  lint:
    name: Lint charts
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch main

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.4.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch main

      - name: Show kubernetes resources (debug)
        if: steps.list-changed.outputs.changed == 'true' || failure()
        run: |
          kubectl get pods --all-namespaces
          kubectl get pvc --all-namespaces
          kubectl get pv --all-namespaces

  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "changedCharts=$changed" >> "$GITHUB_OUTPUT"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Set matrix for build
        id: set-matrix
        run: |
          # See https://stackoverflow.com/a/62953566/11948346
          CHARTS="${{ steps.list-changed.outputs.changedCharts }}"
          JSON="{\"include\":["

          # Loop by lines
          while read chart; do

            # Set $os. "ubuntu-latest" by default.
            os="ubuntu-latest"

            # Add build to the matrix only if it is not already included
            JSONline="{\"directory\": \"$chart\", \"os\": \"$os\"},"
            if [[ "$JSON" != *"$JSONline"* ]]; then
              JSON="$JSON$JSONline"
            fi
          done <<< "$CHARTS"

          # Remove last "," and add closing brackets
          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          echo $JSON

          # Set output
          echo "matrix=$( echo "$JSON" )" >> $GITHUB_OUTPUT

  # kubeval-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.16.8
  #         - v1.17.4
  #         - v1.18.20
  #         - v1.19.16
  #         - v1.20.15
  #         - v1.21.10
  #         - v1.22.7
  #         - v1.23.4
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Submodules
  #       run: git submodule update --init
  #     - name: Run kubeval
  #       env:
  #         KUBERNETES_VERSION: ${{ matrix.k8s }}
  #       run: .github/kubeval.sh

  # minikube-deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #     - kubeval-chart
  #   name: build example and deploy to minikube
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Submodules
  #       run: git submodule update --init
  #     - name: Start Minikube
  #       uses: manusa/actions-setup-minikube@v2.7.2
  #       with:
  #         minikube version: v1.28.0
  #         kubernetes version: v1.25.6
  #     - name: Install YamlQueryTool
  #       uses: mikefarah/yq@v4.33.3
  #     - name: Deploy secrets
  #       run: .github/deploy-secrets.sh
  #     - name: Deploy charts
  #       run: .github/deploy-charts.sh
      # - name: Verify Istio
      #   run: .github/verify-istio.sh
      # - name: Build image
      #   run: |
      #     export SHELL=/bin/bash
      #     eval $(minikube -p minikube docker-env)
      #     docker build -f ./Dockerfile -t local/example .
      #     echo -n "verifying images:"
      #     docker images        
      # - name: Test service URLs
      #   run: |
      #     minikube service list
      #     minikube service example --url
      #     echo "------------------opening the service------------------"
      #     curl $(minikube service example --url)