name: Release Charts

on:
  push:
    branches:
      - main
    # paths:
    #   - 'charts/**'
    #   - '.github/workflows'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Submodules
        run: git submodule update --init

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release Charts
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Login to container registry
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: Pushing Helm Chart
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          cd charts && helm package keycloak
          PKG_NAME=`ls *.tgz`
          helm push ${PKG_NAME} oci://ghcr.io/${REPO_OWNER}/charts