name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Submodules
        run: git submodule update --init

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to Container Registry
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Release Charts to Github Pages
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          CR_SKIP_EXISTING: true
          
      - name: Push Charts to Container Registry
        working-directory: charts
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          for CHART_DIR in $(ls -d */Chart.yaml | cut -d '/' -f 1); do
            CHART_NAME="$(yq '.name' ${CHART_DIR}/Chart.yaml)"
            echo "Packaging ${CHART_NAME} chart"
            helm dependency build ${CHART_DIR}
            helm package ${CHART_DIR}
            PKG_NAME=`ls *.tgz`
            echo "Pushing ${CHART_NAME} chart"
            helm push ${PKG_NAME} oci://ghcr.io/${REPO_OWNER}/charts
            rm ${PKG_NAME}
          done
