apiVersion: v2
name: onlyoffice
description: A Helm chart for OnlyOffice
type: application
version: 0.0.1
dependencies:
  - name: rabbitmq
    version: "8.27.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.deploy
  - name: redis
    version: "16.9.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.deploy
  - name: postgresql
    version: "11.1.28"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.deploy
