replicaCount: 1

# nfs-server-provisioner:
#   deploy: true

mysql:
  deploy: true

rabbitmq:
  deploy: true
  metrics:
    enabled: true

redis:
  deploy: true
  metrics:
    enabled: true
  image:
    debug: true

postgresql:
  deploy: true
  primary:
    initdb:
      scriptsConfigMap: onlyoffice-init-db-scripts
  auth:
    database: postgres
  metrics:
    enabled: true

enabled:
  community: true
  controlpanel: true
  documents: true
  mail: true

jwt:
  enabled: true
  header: "AuthorizationJwt"
  secret: "SNl5Wl+HgQPDqoTFH5SgfnWPZqXkycx6yexQXDBffij4vAfgPZlW9lSE0+5XQ9oP"

image:
  community:
    # repository: jakoberpf/onlyoffice-communityserver
    repository: onlyoffice/communityserver
    pullPolicy: Always
    tag: "latest"
  controlpanel:
    # repository: jakoberpf/onlyoffice-controlpanel
    repository: onlyoffice/controlpanel
    pullPolicy: Always
    tag: "latest"
  documents:
    # repository: jakoberpf/onlyoffice-documentserver
    repository: onlyoffice/documentserver
    pullPolicy: Always
    tag: "latest"
  mail:
    # repository: jakoberpf/onlyoffice-mailserver
    repository: onlyoffice/mailserver
    pullPolicy: Always
    tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  community:
    type: ClusterIP
    ports: 
      http: 80
      https: 443
      websocket: 5222
  controlpanel:
    type: ClusterIP
    ports:
      http: 80
      https: 443
  documents:
    type: ClusterIP
    ports:
      http: 80
      https: 443
  mail:
    type: ClusterIP
    ports:
      smtp: 25
      imap: 143
      smtptls: 587

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
