{{- if .Values.ingress.certManager.enabled -}}
{{- $fullName := include "zerotier-controller.fullname" . -}}
{{- $certManagerLabels := include "zerotier-controller.labels" . -}}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- $certManagerLabels | nindent 4 }}
  {{- with .Values.ingress.certManager.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ $fullName }}
  issuerRef:
    name: {{ .Values.ingress.certManager.issuerRef.name }}
    kind: {{ .Values.ingress.certManager.issuerRef.kind | default "ClusterIssuer" }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"
{{- end }}