apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zerotier-controller.fullname" . }}-ui
  labels:
    {{- include "zerotier-controller.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate # https://www.weave.works/blog/kubernetes-deployment-strategies
  selector:
    matchLabels:
      {{- include "zerotier-controller.selectorLabels" . | nindent 6 }}
      component: ui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zerotier-controller.selectorLabels" . | nindent 8 }}
        component: ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zerotier-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          env:
            - name: ZU_CONTROLLER_ENDPOINT
              value: http://{{ include "zerotier-controller.fullname" . }}:9993/
            - name: ZU_SECURE_HEADERS
              value: "true"
            - name: ZU_DEFAULT_USERNAME
              value: admin
            - name: ZU_DEFAULT_PASSWORD
              value: zero-ui
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/lib/zerotier-one
            name: zerotier-one-data
          - mountPath: /app/backend/data
            name: zerotier-ui-data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: zerotier-one-data
        persistentVolumeClaim:
          claimName: zerotier-one-data
      - name: zerotier-ui-data
        persistentVolumeClaim:
          claimName: zerotier-ui-data
