{{- if and .Values.ui.persistence.enabled .Values.ui.persistence.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.ui.persistence.pvc.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ui.persistence.pvc.size }}
{{- end }}
