{{- if .Values.ui.admin.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ui.admin.secretName }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}

  {{- if .Release.IsInstall }}
  password: {{ randAlphaNum 48 | b64enc }}
  {{ else }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace .Values.ui.admin.secretName).data "password" }}
  {{ end }}
{{- end }}
