apiVersion: v1
kind: Service
metadata:
  name: {{ include "zerotier-controller.fullname" . }}-ui
  labels:
    {{- include "zerotier-controller.labels" . | nindent 4 }}
    component: ui
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zerotier-controller.selectorLabels" . | nindent 4 }}
    component: ui
