apiVersion: v1
kind: Service
metadata:
  name: {{ include "zerotier-controller.fullname" . }}
  labels:
    {{- include "zerotier-controller.labels" . | nindent 4 }}
    component: controller
spec:
  type: ClusterIP
  ports:
    - port: 9993
      targetPort: zerotier
      protocol: TCP
      name: zerotier
  selector:
    {{- include "zerotier-controller.selectorLabels" . | nindent 4 }}
    component: controller
